### ISSUE TITLE
Be explicit about the meaning of empty encryptionScheme

### ISSUE THREAD

**Issue by xhwang-chromium** [joeyparrish/encrypted-media-encryption-scheme#15]
The current proposal clearly defines the meaning of a null encryptionScheme, e.g. how it's can be used for backward compatibility purposes. But it's unclear how the user agent should handle non-null but empty encryptionScheme. Does it mean any encryptionScheme, or it should never be supported? The spec should be explicit about this case. Thanks!

**Comment by joeyparrish** [comment]
I agree that it might help to be more explicit.

Though I wasn't explicit, I would think it implied that an empty string would be an unrecognized scheme and therefore be rejected.

On the other hand, making an empty string equivalent to null would make very little difference.

Does anyone have a strong opinion either way?
