### ISSUE TITLE
Merge into W3C repo and archive the WICG repo

### ISSUE THREAD

**Issue by tidoust** [joeyparrish/encrypted-media-encryption-scheme#16]
The feature described in this repo is now in scope of the Media Working Group.

It would be good to merge relevant spec updates back into the main [w3c/encrypted-media](https://github.com/w3c/encrypted-media/) repo (at least as a pull request) so that we can point people at the right place and archive this repository. @joeyparrish, how would you like to proceed?

**Comment by joeyparrish** [comment]
This proposal has already been merged into w3c/encrypted-media.  What's the procedure to archive this and point people back to the main spec?  I'm not very experienced in the W3C yet.

**Comment by tidoust** [comment]
Good! The way I would do it:

- [x] Add a warning at the beginning of the README along the lines of "This proposal has been integrated into the parent [Encrypted Media Extensions](https://w3c.github.io/encrypted-media/) specification, developed by the [Media Working Group](https://www.w3.org/media-wg/)."
- [x] Add a redirect in [WICG/wicg.github.io](https://github.com/WICG/wicg.github.io/) to redirect the spec at wicg.github.io to the one at w3c.github.io.
- [ ] Ask WICG chairs to review and to archive the repository.

Happy to take care of it.

**Comment by joeyparrish** [comment]
The README has been updated, and issues have been transferred to the main spec issue tracker.  I appear to have rights to archive this repo myself, so I'll go ahead and do that.  Thanks!
