### ISSUE TITLE
Including Associated SystemID

### ISSUE THREAD

**Issue by KilroyHughes** [joeyparrish/encrypted-media-encryption-scheme#3]
Consider reporting the CENC SystemID paired with the associated CENC encryption scheme.
An application needs to find a device capability that combines both in order to download a key, decrypt, decode, and output the media. 

For instance, a device might have the capability to decrypt 'cbcs' when using the FairPlay key management system, and 'cenc' when using the Widevine DRM license system. Simply reporting both decryption schemes are supported in the device doesn't tell the application which key management system and scheme combination will work together. 

A CDM normally corresponds to a single SystemID, but may implement either or both decryption schemes. The SystemID of the CDM conveys additional capabilities that may be required for the application, e.g. are DRM licenses supported or simply cert bound key delivery? What output controls are supported by the CDM? UHD level security? Time limited licenses (rental)? Region limited licenses? Hierarchical licenses and leaf licenses stored in media Fragments for broadcast? 
An application can determine many CDM functional capabilities from a SystemID and linked specifications registered at https://dashif.org/identifiers/protection/  Querying other DRM functions by parameter, as proposed for the CENC encryption scheme, isn't practical because there are too many, and functionality is often similar but different between SystemIDs, not conforming to a common specification like common encryption.

**Comment by joeyparrish** [comment]
I'm not sure I understand your comment.  A query in EME is already specific to one key system ID.  For example, the `keySystem` variable below:

```js
  navigator.requestMediaKeySystemAccess(keySystem, [{
    videoCapabilities: [
      { // A capability object which uses the "cenc" encryption scheme
        contentType: 'video/mp4; codecs="avc1.640028"',
        encryptionScheme: 'cenc',
      },
      { // A capability object which uses the "cbcs" encryption scheme
        contentType: 'video/mp4; codecs="avc1.640028"',
        encryptionScheme: 'cbcs',
      },
    ],
    initDataTypes: ['keyids'],
  }]);
```

That query checks for both 'cbcs' and 'cenc' in one particular key system.  So the application already knows what key system it's talking about.  Here's another example showing ways to identify the key system:

```js
  const config = {
    videoCapabilities: [
      { // A capability object which uses the "cenc" encryption scheme
        contentType: 'video/mp4; codecs="avc1.640028"',
        encryptionScheme: 'cenc',
      },
      { // A capability object which uses the "cbcs" encryption scheme
        contentType: 'video/mp4; codecs="avc1.640028"',
        encryptionScheme: 'cbcs',
      },
    ],
    initDataTypes: ['keyids'],
  };

  let access;
  try {
    access = await navigator.requestMediaKeySystemAccess('com.ks1', [config]);

    // The key system ID is known from the state of the code.  If we're here, it's KS1.
    console.log('Found a working config for KS1!');
  } catch () {
    access = await navigator.requestMediaKeySystemAccess('com.ks2', [config]); 

    // The key system ID is known from the state of the code.  If we're here, it's KS2.
    console.log('Found a working config for KS2!');
  }

  // The key system ID is also known from the access object.
  console.log('Key system is', access.keySystem);
```

**Comment by joeyparrish** [comment]
If I misunderstood your question, could you maybe give some sample code to help explain what you're asking for?

**Comment by joeyparrish** [comment]
@KilroyHughes, ping!

**Comment by joeyparrish** [comment]
Since there has been no update for a few months, I'm going to close this issue.  Please let me know if we need to reopen it to discuss further.  Thanks!
