### ISSUE TITLE
Including 'profiles' MIME subparameter

### ISSUE THREAD

**Issue by KilroyHughes** [joeyparrish/encrypted-media-encryption-scheme#4]
RFC 6381 defines the subparameters for ISOBMFF files, and media specifications define the values appropriate for each codec and encoding. For instance, in your example:

```js
videoCapabilities: [{
        contentType: 'video/mp4; codecs="avc1.640028"',
        encryptionScheme: 'cenc',
      }],
```

It would be useful if the 'profiles' subparameter was supported in addition to the 'codecs' subparameter, e.g.:

```js
videoCapabilities: [{
        contentType: 'video/mp4; codecs="avc1.640028"; profiles="iso9, cmfc, avch"',
        encryptionScheme: 'cenc',
      }],
```

For an ISOBMFF file or CMAF stream, the parameters are the compatibility brands stored in the file type box. In this example, the four character code 'iso9' indicates the ISOBMFF container parser required by the content or supported by the device. 'cmfc' indicates CMAF container constraints, such as all media samples contained in movie fragments, all movie fragments contain a 'tfdt' timestamp and are optimized for adaptive splicing in an MSE buffer. 'avch' is one example of a "Media Profile" brand, which can indicate constraints on the elementary stream, containment of media samples, differences between tracks in Switching Sets, etc. that a device must support for seamless adaptive switching and scaling using a CMAF specified late binding, synchronization, pipeline initialization, and rendering model. The 'codecs' subparameter includes the codec profile and level, but nothing about being able to parse and adaptively splice, decode, and render movie fragments from different files seamlessly. 

Compatibility brands provide a simple code point in content and devices to identify interoperability, but the code point may represent several pages of constraints on specifications such as ISOBMFF and AVC, which have thousands of parameters and options that can combine to prevent interoperability between content and devices with the same 'codecs' parameter, unless constrained to a specific Media Profile.

**Comment by joeyparrish** [comment]
I don't think these compatibility brands are related to this encryption scheme proposal.  I think this might be better addressed as an issue on the main EME spec: https://github.com/w3c/encrypted-media/issues

Please note that this repository is for incubating one small feature: encryption scheme querying.  This is **not** an all-encompassing EME v2.  Thanks!

**Comment by joeyparrish** [comment]
@KilroyHughes, do you feel there is more to discuss on this?  Or may I close the issue?

**Comment by KilroyHughes** [comment]
Yes, I consider it resolved as out of your intended scope.

Kilroy Hughes

________________________________

**Comment by joeyparrish** [comment]
Thanks!
