### ISSUE TITLE
Create a registry for encryption schemes

### ISSUE THREAD

**Issue by ddorwin** [joeyparrish/encrypted-media-encryption-scheme#9]
The specified encryption schemes (or at least their names) are ISO CENC-specific, but EME and HTML5 are format-independent (media formats are not referenced in these specs).

This could probably be addressed in one of a few ways:
1. Define valid values in a registry - or the [Stream Format Registry](https://www.w3.org/TR/eme-stream-registry/) entry for the specified content type. (This wouldn’t work for an enum, but it probably shouldn't be an enum anyway - see https://github.com/WICG/encrypted-media-encryption-scheme/issues/8.)
1. Independently define the schemes and use generic names (i.e., "cbc-skip"). This is more work with little gain.
1. Decide to include these definitions in the main spec and to apply to any media stream format. This seems a bit difficult to rationalize.

(1) seems like the best approach.

**Comment by joeyparrish** [comment]
In internal discussion, a registry has won out.  There are many good reasons, but the most compelling for me is that AES-128 won't last forever.  No matter how much we want to avoid proliferation of schemes with differing cipher modes as in CBC vs CTR, it would be foolish to assume we'll never move to anything other than the two main schemes in use today.

@ddorwin, with your blessing, I will close this issue, open a new one specifically about the creation of a registry (on which I will need guidance), and update #8 and #12 with relevant details.

**Comment by ddorwin** [comment]
That sounds good to me.

As noted in (1) above, it may not be that we need a _new_ registry but that we can specify the values in the existing [Stream Format Registry](https://w3c.github.io/encrypted-media/format-registry/stream/) entries, specifically in https://w3c.github.io/encrypted-media/format-registry/stream/mp4.html. That specific entry needs to be updated anyway because it specifies that such content "shall be encrypted at the sample level with AES-128 CTR encryption."

The meaning of no value can also be specified in each registry entry. Thus, https://github.com/WICG/encrypted-media-encryption-scheme/issues/10 only applies to ISO BMFF (MP4) and not the core spec or WebM [1]. A hypothetical future format could even require an `encryptionScheme` value.

[1] https://w3c.github.io/encrypted-media/format-registry/stream/webm.html should updated to specify whether any values are supported and that the default is what it currently says.

**Comment by mounirlamouri** [comment]
I would be interested why the registry approached win the internal discussions. Do we expect a flood of types coming our way or just that one will once be added and another removed? I would actually use the Stream Format Registry as an example on how registries are often not a very good idea: this registry has two entries and has been around for 3 years now. We are now working on a new version of EME which could easily include any new version of this list if need be.

**Comment by mrstux** [comment]
A specification which defines a mechanism to check format compatibility shouldn’t need a revision just because another specification later defines an additional format. 

That is the problem the registry solves,

But for exposition reasons, I’d suggest leaving the cenc/cbcs examples in place and refer to the registry for the definitive list.

**Comment by joeyparrish** [comment]
I've renamed this issue and marked it as an enhancement to create a registry for encryption schemes.
